services:
  postgres:
    image: postgres
    container_name: notify_db
    env_file:
      - .env
    volumes:
      - ./etc/schema_design/:/docker-entrypoint-initdb.d/
      - ./database:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  notify_admin:
    env_file:
      - .env
    build: notify_admin_panel
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
