# Generated by Django 3.2 on 2024-04-02 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name', max_length=250, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Template description', null=True, verbose_name='Description')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Templates',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('user_id', models.CharField(help_text='User ID', max_length=255)),
                ('email', models.CharField(help_text='Email', max_length=255)),
                ('event_type', models.CharField(choices=[('period', 'Period'), ('now', 'Moment')], default='period', max_length=50, verbose_name='Event type')),
                ('every_day', models.IntegerField(blank=True, null=True, verbose_name='Every_day')),
                ('processed', models.DateTimeField(blank=True, null=True, verbose_name='Processed')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
    ]
