version: '3.8'

services:

  notify:
    container_name: notify
    restart: always
    build: ./
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 15s
      timeout: 2s
      retries: 15

  admin_notifications:
    container_name: admin_notifications
    build:
      context: ./admin_notice
      dockerfile: ./Dockerfile
    command: /bin/bash -c "gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./admin_notice/static_volume:/code/static/
#    restart: always
    env_file:
      - ./admin_notice/.env.example
    ports:
      - "${DJANGO_ADMIN_NOTICE_PORT}:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notify