name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - if: ${{ matrix.python-version != 3.7 }}
      run:  pip install requests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r like_api/requirements_files_for_GH_actions/requirements-${{ matrix.python-version }}.txt
        pip install wemake-python-styleguide
        pip install mypy
    - name: Analysing the code with wemake-python-styleguide
      run: |
        flake8 $(git ls-files '*.py')
    - uses: actions/upload-artifact@v4
      with:
        name: res_linter-python-${{ matrix.python-version }}.html
        path: res_linter.html
    - name: Analysing type checking with mypy
      run: |
        mypy $(git ls-files '*.py')

